#include <asm/host_ops.h>
#include <asm/cpu.h>
#include <linux/sched.h>
#include <linux/sched/signal.h>
#include <asm-generic/ucontext.h>

void lkl_do_trap(int trapnr, int signr, char *str, struct ucontext *uctx,
		 long error_code, struct siginfo *info)
{
	long ret;

	/* BUG: kernel not ready to process trap */
	BUG_ON(!lkl_is_running());

	/* Acquire lock to ensure that syscall trigger will
	 * not consume the signal generated by lkl_do_trap */
	ret = lkl_cpu_get();

	/* Failing to trap lead to inconsistent system, so trigger panic */
        if (ret < 0) {
                lkl_ops->panic();
                return;
        }

	force_sig_info((struct kernel_siginfo *)info);
	lkl_process_trap(signr, uctx);

	lkl_cpu_put();
}
